### PR TITLE
Replace ob_start with http2_link_preload_header in add_action

### LINKED ISSUE #2: Various Errors
On the admin side: 
`Warning: Cannot modify header information - headers already sent by (output started at /srv/www/master/html/wp-includes/script-loader.php:1147) in /wp-content/plugins/http2-server-push/http2-server-push.php on line 35`

Front-end:
`Warning: ob_start(): function '' not found or invalid function name in /srv/www/master/html/wp-includes/plugin.php on line 525`

`Notice: ob_start(): failed to create buffer in /srv/www/master/html/wp-includes/plugin.php on line 525`

I'm sure this is probably due to random plugins on my end, but wanted to note it somewhere as it'd be nice to be able to determine a way to work around it.

### PR DESCRIPTION
**Pull request by suzannealdrich**
Replace ob_start with http2_link_preload_header in add_action to fix https://github.com/daveross/http2-server-push/issues/2

### CODE REVIEW

**Comment by suzannealdrich** [comment]
Hi @daveross - Do you think you could take a moment to review this pull request? I'm using my version in production, and not experiencing the error referenced in my commit message anymore. I work at CloudFlare, and we just released HTTP/2 Server Push for all our customers. Here is our [documentation](https://support.cloudflare.com/hc/en-us/articles/218367338-HTTP-2-Server-Push) and [blog post on the release](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/), where we mention that there are 3rd party plugins available for WordPress, aka yours. There are complaints from users about the release version breaking their sites, so it would be nice if you could verify my bugfix is appropriate, and merge this very soon.

**Comment by dana-ross** [comment]
Hi @suzannealdrich ! Sorry for not seeing this sooner. I don't recall seeing any emails about your pull request until you included the @daveross in your comment. I'll definitely look into that.

Thanks for the patch, but I think it's critical to keep the ob_start() call in there. It's pretty much guaranteed that a plugin or theme is going to be outputting things before WordPress goes to print out script & style tags, and the output buffer is the only way to make sure the HTTP headers get through without errors.

Could you try the code in the `bugfix/ob-start` branch and see if that clears things up? If so, I can get a new production version out ASAP.

**Comment by dana-ross** [comment]
Hi @suzannealdrich - I released v1.1 on WordPress.org this evening. Let me know if your customers continue to have errors. Thanks!

**Comment by suzannealdrich** [comment]
I can verify that your v1.1 release fixed the error I experienced previously. Thanks for fixing it up!

**Pull request closed without merging**
